[project]
name = "robofy-backend"
version = "0.1.0"
description = "Robofy AI backend service"
requires-python = ">=3.13"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"